-- Hand-authored migration (not generated by `prisma migrate dev`, since Prisma's
-- schema.prisma cannot express foreign keys into Supabase's `auth` schema, check
-- constraints, triggers, security-definer functions, or RLS policies). Applies
-- cleanly after 20260101000000_init via `prisma migrate deploy`.

-- =========================================================================
-- 1. Foreign keys into auth.users (not modeled in Prisma — see schema.prisma)
-- =========================================================================
alter table "profiles"
  add constraint "profiles_user_id_fkey"
  foreign key ("user_id") references auth.users (id) on delete cascade;

alter table "family_members"
  add constraint "family_members_user_id_fkey"
  foreign key ("user_id") references auth.users (id) on delete set null;

-- =========================================================================
-- 2. Data validation: CHECK constraints (never trust the frontend alone)
-- =========================================================================
alter table "transactions"
  add constraint "transactions_amount_positive" check ("amount" > 0);

alter table "transactions"
  add constraint "transactions_transfer_needs_destination"
  check (
    ("type" <> 'transfer') or
    ("transfer_to_account_id" is not null and "transfer_to_account_id" <> "account_id")
  );

alter table "recurring_transactions"
  add constraint "recurring_transactions_amount_positive" check ("amount" > 0);

alter table "recurring_transactions"
  add constraint "recurring_transactions_interval_positive" check ("interval" > 0);

alter table "recurring_transactions"
  add constraint "recurring_transactions_transfer_needs_destination"
  check (
    ("type" <> 'transfer') or
    ("transfer_to_account_id" is not null and "transfer_to_account_id" <> "account_id")
  );

alter table "budgets"
  add constraint "budgets_amount_non_negative" check ("amount" >= 0);

alter table "savings_goals"
  add constraint "savings_goals_target_positive" check ("target_amount" > 0);

alter table "savings_goals"
  add constraint "savings_goals_current_non_negative" check ("current_amount" >= 0);

-- =========================================================================
-- 3. updated_at bookkeeping — @updatedAt in schema.prisma only fires when
--    writes go through Prisma Client; this app writes exclusively through
--    supabase-js, so the timestamp needs a real DB trigger.
-- =========================================================================
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

do $$
declare
  t text;
begin
  foreach t in array array[
    'profiles', 'families', 'family_members', 'categories', 'accounts',
    'transactions', 'recurring_transactions', 'budgets', 'savings_goals',
    'quick_add_presets'
  ]
  loop
    execute format(
      'create trigger set_updated_at before update on %I for each row execute function public.set_updated_at();',
      t
    );
  end loop;
end;
$$;

-- =========================================================================
-- 4. Cross-family referential integrity for transactions / recurring rows
--    (category/account/member must belong to the same family as the txn)
-- =========================================================================
create or replace function public.check_transaction_family_consistency()
returns trigger
language plpgsql
as $$
begin
  if new.category_id is not null and not exists (
    select 1 from public.categories c where c.id = new.category_id and c.family_id = new.family_id
  ) then
    raise exception 'category % does not belong to family %', new.category_id, new.family_id;
  end if;

  if new.account_id is not null and not exists (
    select 1 from public.accounts a where a.id = new.account_id and a.family_id = new.family_id
  ) then
    raise exception 'account % does not belong to family %', new.account_id, new.family_id;
  end if;

  if new.transfer_to_account_id is not null and not exists (
    select 1 from public.accounts a where a.id = new.transfer_to_account_id and a.family_id = new.family_id
  ) then
    raise exception 'transfer_to_account % does not belong to family %', new.transfer_to_account_id, new.family_id;
  end if;

  if new.member_id is not null and not exists (
    select 1 from public.family_members m where m.id = new.member_id and m.family_id = new.family_id
  ) then
    raise exception 'member % does not belong to family %', new.member_id, new.family_id;
  end if;

  return new;
end;
$$;

create trigger check_family_consistency
  before insert or update on "transactions"
  for each row execute function public.check_transaction_family_consistency();

create trigger check_family_consistency
  before insert or update on "recurring_transactions"
  for each row execute function public.check_transaction_family_consistency();

-- =========================================================================
-- 5. Account balance maintenance — keeps accounts.current_balance correct
--    across insert / edit / soft-delete / restore / hard-delete of a
--    transaction, without double-counting. Transfers move money between two
--    accounts and are never treated as income or expense.
-- =========================================================================
create or replace function public.apply_transaction_balance_delta(
  p_account_id uuid,
  p_transfer_to_account_id uuid,
  p_type "transaction_type",
  p_amount numeric,
  p_sign int -- +1 to apply, -1 to reverse
)
returns void
language plpgsql
as $$
begin
  if p_type = 'expense' then
    update public.accounts set current_balance = current_balance - (p_sign * p_amount) where id = p_account_id;
  elsif p_type = 'income' then
    update public.accounts set current_balance = current_balance + (p_sign * p_amount) where id = p_account_id;
  elsif p_type = 'transfer' then
    update public.accounts set current_balance = current_balance - (p_sign * p_amount) where id = p_account_id;
    update public.accounts set current_balance = current_balance + (p_sign * p_amount) where id = p_transfer_to_account_id;
  end if;
end;
$$;

create or replace function public.sync_account_balance()
returns trigger
language plpgsql
as $$
begin
  if tg_op = 'INSERT' then
    if not new.is_deleted and new.account_id is not null then
      perform public.apply_transaction_balance_delta(
        new.account_id, new.transfer_to_account_id, new.type, new.amount, 1
      );
    end if;
    return new;
  elsif tg_op = 'UPDATE' then
    if not old.is_deleted and old.account_id is not null then
      perform public.apply_transaction_balance_delta(
        old.account_id, old.transfer_to_account_id, old.type, old.amount, -1
      );
    end if;
    if not new.is_deleted and new.account_id is not null then
      perform public.apply_transaction_balance_delta(
        new.account_id, new.transfer_to_account_id, new.type, new.amount, 1
      );
    end if;
    return new;
  elsif tg_op = 'DELETE' then
    if not old.is_deleted and old.account_id is not null then
      perform public.apply_transaction_balance_delta(
        old.account_id, old.transfer_to_account_id, old.type, old.amount, -1
      );
    end if;
    return old;
  end if;
  return null;
end;
$$;

create trigger sync_account_balance
  after insert or update or delete on "transactions"
  for each row execute function public.sync_account_balance();

-- =========================================================================
-- 6. Family membership helper (SECURITY DEFINER so RLS on family_members
--    does not need to recursively re-check itself) + RPC to atomically
--    create a family, its first member, and default categories/accounts.
-- =========================================================================
create or replace function public.current_family_ids()
returns setof uuid
language sql
security definer
stable
set search_path = public
as $$
  select family_id from public.family_members where user_id = auth.uid();
$$;

create or replace function public.create_family_with_defaults(
  p_family_name text,
  p_member_name text,
  p_currency text default 'INR'
)
returns public.families
language plpgsql
security definer
set search_path = public
as $$
declare
  v_family public.families;
  v_expense_categories text[][] := array[
    array['Food', '🍔'], array['Groceries', '🛒'], array['Home', '🏠'],
    array['Utilities', '💡'], array['Transport', '🚗'], array['Fuel', '⛽'],
    array['Medical', '🏥'], array['Medicine', '💊'], array['Shopping', '🛍️'],
    array['Clothing', '👕'], array['Mobile', '📱'], array['Internet', '🌐'],
    array['Entertainment', '🎬'], array['Travel', '✈️'], array['Education', '🎓'],
    array['Children', '👶'], array['Pets', '🐶'], array['Bills', '💳'],
    array['Loan', '🏦'], array['Subscriptions', '📦'], array['Gifts', '🎁'],
    array['Investments', '💰'], array['Other', '📋']
  ];
  v_income_categories text[][] := array[
    array['Salary', '💼'], array['Bonus', '💰'], array['Interest', '🏦'],
    array['Investment', '📈'], array['Gift', '🎁'], array['Other', '💵']
  ];
  v_accounts text[][] := array[
    array['Cash', 'cash'], array['Bank Account', 'bank'],
    array['Credit Card', 'credit_card'], array['UPI', 'upi']
  ];
  v_row text[];
begin
  if exists (select 1 from public.family_members where user_id = auth.uid()) then
    raise exception 'You already belong to a family.';
  end if;

  insert into public.families (name, currency) values (p_family_name, p_currency)
  returning * into v_family;

  insert into public.family_members (family_id, user_id, name, is_active)
  values (v_family.id, auth.uid(), p_member_name, true);

  insert into public.profiles (user_id, full_name)
  values (auth.uid(), p_member_name)
  on conflict (user_id) do nothing;

  foreach v_row slice 1 in array v_expense_categories loop
    insert into public.categories (family_id, name, type, icon, is_default)
    values (v_family.id, v_row[1], 'expense', v_row[2], true);
  end loop;

  foreach v_row slice 1 in array v_income_categories loop
    insert into public.categories (family_id, name, type, icon, is_default)
    values (v_family.id, v_row[1], 'income', v_row[2], true);
  end loop;

  foreach v_row slice 1 in array v_accounts loop
    insert into public.accounts (family_id, name, type, opening_balance, current_balance)
    values (v_family.id, v_row[1], v_row[2]::public.account_type, 0, 0);
  end loop;

  return v_family;
end;
$$;

-- =========================================================================
-- 7. Row Level Security — a user may only ever read/write data that belongs
--    to a family they are a member of. Never expose the service-role key;
--    all of this is enforced for the anon-key + authenticated JWT context.
-- =========================================================================
alter table "profiles" enable row level security;
alter table "families" enable row level security;
alter table "family_members" enable row level security;
alter table "categories" enable row level security;
alter table "accounts" enable row level security;
alter table "transactions" enable row level security;
alter table "recurring_transactions" enable row level security;
alter table "budgets" enable row level security;
alter table "savings_goals" enable row level security;
alter table "quick_add_presets" enable row level security;

-- profiles: a user may only see/edit their own profile row
create policy "profiles_select_own" on "profiles" for select using (user_id = auth.uid());
create policy "profiles_insert_own" on "profiles" for insert with check (user_id = auth.uid());
create policy "profiles_update_own" on "profiles" for update using (user_id = auth.uid()) with check (user_id = auth.uid());

-- families: visible/editable only to members of that family
create policy "families_select_member" on "families" for select using (id in (select public.current_family_ids()));
create policy "families_update_member" on "families" for update using (id in (select public.current_family_ids())) with check (id in (select public.current_family_ids()));
-- families are created exclusively via create_family_with_defaults(); no direct insert/delete policy.

-- family_members: visible/editable only to members of that family
create policy "family_members_select_member" on "family_members" for select using (family_id in (select public.current_family_ids()));
create policy "family_members_insert_member" on "family_members" for insert with check (family_id in (select public.current_family_ids()));
create policy "family_members_update_member" on "family_members" for update using (family_id in (select public.current_family_ids())) with check (family_id in (select public.current_family_ids()));
create policy "family_members_delete_member" on "family_members" for delete using (family_id in (select public.current_family_ids()));

-- categories
create policy "categories_select_member" on "categories" for select using (family_id in (select public.current_family_ids()));
create policy "categories_insert_member" on "categories" for insert with check (family_id in (select public.current_family_ids()));
create policy "categories_update_member" on "categories" for update using (family_id in (select public.current_family_ids())) with check (family_id in (select public.current_family_ids()));
create policy "categories_delete_member" on "categories" for delete using (family_id in (select public.current_family_ids()));

-- accounts
create policy "accounts_select_member" on "accounts" for select using (family_id in (select public.current_family_ids()));
create policy "accounts_insert_member" on "accounts" for insert with check (family_id in (select public.current_family_ids()));
create policy "accounts_update_member" on "accounts" for update using (family_id in (select public.current_family_ids())) with check (family_id in (select public.current_family_ids()));
create policy "accounts_delete_member" on "accounts" for delete using (family_id in (select public.current_family_ids()));

-- transactions
create policy "transactions_select_member" on "transactions" for select using (family_id in (select public.current_family_ids()));
create policy "transactions_insert_member" on "transactions" for insert with check (family_id in (select public.current_family_ids()));
create policy "transactions_update_member" on "transactions" for update using (family_id in (select public.current_family_ids())) with check (family_id in (select public.current_family_ids()));
create policy "transactions_delete_member" on "transactions" for delete using (family_id in (select public.current_family_ids()));

-- recurring_transactions
create policy "recurring_transactions_select_member" on "recurring_transactions" for select using (family_id in (select public.current_family_ids()));
create policy "recurring_transactions_insert_member" on "recurring_transactions" for insert with check (family_id in (select public.current_family_ids()));
create policy "recurring_transactions_update_member" on "recurring_transactions" for update using (family_id in (select public.current_family_ids())) with check (family_id in (select public.current_family_ids()));
create policy "recurring_transactions_delete_member" on "recurring_transactions" for delete using (family_id in (select public.current_family_ids()));

-- budgets
create policy "budgets_select_member" on "budgets" for select using (family_id in (select public.current_family_ids()));
create policy "budgets_insert_member" on "budgets" for insert with check (family_id in (select public.current_family_ids()));
create policy "budgets_update_member" on "budgets" for update using (family_id in (select public.current_family_ids())) with check (family_id in (select public.current_family_ids()));
create policy "budgets_delete_member" on "budgets" for delete using (family_id in (select public.current_family_ids()));

-- savings_goals
create policy "savings_goals_select_member" on "savings_goals" for select using (family_id in (select public.current_family_ids()));
create policy "savings_goals_insert_member" on "savings_goals" for insert with check (family_id in (select public.current_family_ids()));
create policy "savings_goals_update_member" on "savings_goals" for update using (family_id in (select public.current_family_ids())) with check (family_id in (select public.current_family_ids()));
create policy "savings_goals_delete_member" on "savings_goals" for delete using (family_id in (select public.current_family_ids()));

-- quick_add_presets
create policy "quick_add_presets_select_member" on "quick_add_presets" for select using (family_id in (select public.current_family_ids()));
create policy "quick_add_presets_insert_member" on "quick_add_presets" for insert with check (family_id in (select public.current_family_ids()));
create policy "quick_add_presets_update_member" on "quick_add_presets" for update using (family_id in (select public.current_family_ids())) with check (family_id in (select public.current_family_ids()));
create policy "quick_add_presets_delete_member" on "quick_add_presets" for delete using (family_id in (select public.current_family_ids()));

-- =========================================================================
-- 8. Grants — anon/authenticated hit PostgREST with the anon key; RLS above
--    is what actually restricts rows, these grants just allow the role to
--    reach the tables/sequences/functions at all.
-- =========================================================================
grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on all tables in schema public to authenticated;
grant execute on function public.create_family_with_defaults(text, text, text) to authenticated;
grant execute on function public.current_family_ids() to authenticated;
